#!/usr/bin/env bash
# Install nginx on a server; add a string
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School." | sudo tee /usr/share/nginx/html/index.html
