#!/usr/bin/env bash
# Set up new nginx; redirect to different site
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "36i\      rewrite ^/redirect_me https://www.youtube.com/watch?v=i6l8MFdTaPE permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
