#!/usr/bin/env bash
# Install nginx; build cusom 404 page

sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
echo "" >> /usr/share/nginx/html/custom_404.html
sudo sed -i "36i\      rewrite ^/redirect_me https://www.youtube.com/ permanent;" /etc/nginx/sites-enabled/default
sudo sed -i "44i\        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                root /usr/share/nginx/html;\n                internal;\n        }" /etc/nginx/sites-enabled/default
sudo service nginx start
