#!/usr/bin/env bash
# Configure web-02 nginx server
sudo apt-get install -y nginx;
sudo sed -i "29i\        rewrite ^/redirect_me https://www.youtube.com permanent;\n       proxy_set_header X-Served-By $HOSTNAME" /etc/nginx/sites-enabled/default;
echo "Holberton School web-02." | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
