#!/usr/bin/env bash
# Configure web-02 nginx server
sudo apt-get update
sudo apt-get install -y nginx;
echo "Holberton School web-02." | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "37i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
