#!/usr/bin/env bash
# This script prints number 1 to 20, whith bad luck statements.
COUNTER=1
while [ $COUNTER -lt 21 ]; do
    echo $COUNTER
    case $COUNTER in
	4)
	        echo "bad luck from China";;
	9)
	        echo "bad luck from Japan";;
	17)
	        echo "bad luck from Italy";;
    esac
    let COUNTER=COUNTER+1
done
