#!/usr/bin/env bash
# This script prints number 1 to 20, whith bad luck statements.
i=1
while ((i < 21))
do
	if ((i == 5)); then
	   echo $"bad luck from China"
	elif ((i == 10)); then
	     echo $"bad luck from Japan"
	elif ((i == 18)); then
	     echo $"bad luck from Italy"
	fi
	echo $i
	((i++))
done
